### PR TITLE
created protective curtain keyword

### PR DESCRIPTION
**Pull request by thea-m**

### CODE REVIEW

**Comment by thea-m** [comment]
As always, I could not transform the schema after adding this keyword according to the steps detailed in the guidelines (transformation failed). Could you edit the schema?

**Comment by PietroLiuzzo** [comment]
this is a bit strange, with the latest oxygen especially. can you please make sure your TEI package is updated?

**Review by PietroLiuzzo — APPROVED** [review]

**Comment by thea-m** [comment]
I don't have the latest oXygen on my laptop. How can I update the TEI package?

**Comment by PietroLiuzzo** [comment]
I think you go to preferences, add-ons, click add and point it to https://www.tei-c.org/release/oxygen/updateSite.oxygen

**Comment by thea-m** [comment]
The transformation still fails. Maybe it is due to the old oxygen. I don't think it's dramatic, I don't need to edit the schema too often.

**Comment by PietroLiuzzo** [comment]
ok

**Pull request merged**
