### PR TITLE
renamed

### PR DESCRIPTION
**Pull request by thea-m**
@gnizla  @GueshSol 
https://github.com/BetaMasaheft/Authority-Files/pull/27
@eu-genia : renaming the file and moving it to the Art Themes folder. Is that allright?

### CODE REVIEW

**Comment by eu-genia** [comment]
I will check on the backend for doublets when merged - but is changing ID necessary?

**Comment by gnizla** [comment]
I have renamed ATs in the past, so it was feasible once. I think it is important for AT to have recognizable names as most people are going to use those as a reference point for identifying whether a theme exists or not. That's my two cents of course. Thanks both.

**Comment by thea-m** [comment]
Thank you @eu-genia

**Comment by GueshSol** [comment]
Thank you all of you @***@***.*** and @thea-m

**Pull request merged**
